module add32(clk,a,b,sum);
input clk;
input [31:0]a;
input [31:0]b;
output [32:0]sum;
reg [32:0] sum;
always @(posedge clk)
begin
sum=a+b;
end
endmodule

============================================================
  Generated by:           Genus(TM) Synthesis Solution 21.14-s082_1
  Generated on:           Sep 24 2025  10:12:00 am
  Module:                 add32
  Technology library:     typical 
  Operating conditions:   typical (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

 Instance    Module     Cell Count  Cell Area  Net Area   Total Area   Wireload  
---------------------------------------------------------------------------------
add32                          480      0.000     0.000        0.000 <none> (D)  
  add_9_6 add_unsigned         447      0.000     0.000        0.000 <none> (D)  
  (D) = wireload is default in technology library


// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Sep 24 2025 10:12:27 IST (Sep 24 2025 04:42:27 UTC)

// Verification Directory fv/add32 

module add_unsigned(A, B, Z);
  input [31:0] A, B;
  output [32:0] Z;
  wire [31:0] A, B;
  wire [32:0] Z;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_208, n_209;
  wire n_210, n_211, n_212, n_213, n_214, n_215, n_216, n_217;
  wire n_218, n_219, n_220, n_221, n_222, n_223, n_224, n_225;
  wire n_226, n_227, n_228, n_229, n_230, n_231, n_232, n_233;
  wire n_234, n_235, n_236, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_249;
  wire n_250, n_251, n_252, n_253, n_254, n_255, n_256, n_257;
  wire n_258, n_259, n_260, n_261, n_262, n_263, n_264, n_265;
  wire n_266, n_267, n_268, n_269, n_270, n_271, n_272, n_273;
  wire n_274, n_275, n_276, n_277, n_278, n_279, n_280, n_281;
  wire n_282, n_283, n_284, n_285, n_286, n_287, n_288, n_289;
  wire n_290, n_291, n_292, n_293, n_294, n_295, n_296, n_297;
  wire n_298, n_299, n_300, n_301, n_302, n_303, n_304, n_305;
  wire n_306, n_307, n_308, n_309, n_310, n_311, n_312, n_313;
  wire n_314, n_315, n_316, n_317, n_318, n_319, n_320, n_321;
  wire n_322, n_323, n_324, n_325, n_326, n_327, n_328, n_329;
  wire n_330, n_331, n_332, n_333, n_334, n_335, n_336, n_337;
  wire n_338, n_339, n_340, n_341, n_342, n_343, n_344, n_345;
  wire n_346, n_347, n_348, n_349, n_350, n_351, n_352, n_353;
  wire n_354, n_355, n_356, n_357, n_358, n_359, n_360, n_361;
  wire n_362, n_363, n_364, n_365, n_366, n_367, n_368, n_369;
  wire n_370, n_371, n_372, n_373, n_374, n_375, n_376, n_377;
  wire n_378, n_379, n_380, n_381, n_382, n_383, n_384, n_385;
  wire n_386, n_387, n_388, n_389, n_390, n_391, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401;
  wire n_402, n_403, n_404, n_405, n_406, n_407, n_408, n_409;
  wire n_410, n_411, n_412, n_413, n_414, n_415, n_416, n_417;
  wire n_418, n_419, n_420, n_421, n_422, n_423, n_424, n_425;
  wire n_426, n_427, n_428, n_429, n_430, n_431, n_432, n_433;
  wire n_434, n_435, n_436, n_437, n_438, n_439, n_440, n_441;
  wire n_442, n_443, n_444, n_445, n_446, n_447, n_448, n_449;
  wire n_450, n_451, n_452, n_453, n_454, n_455, n_456, n_457;
  wire n_458, n_459, n_460, n_461, n_462, n_463, n_464, n_465;
  wire n_466, n_467, n_468, n_469, n_470, n_471, n_472, n_473;
  wire n_474, n_475, n_476, n_477, n_478, n_479, n_480, n_481;
  wire n_482, n_483, n_484, n_485, n_486, n_487, n_488, n_489;
  wire n_490, n_491, n_492, n_493, n_494, n_495, n_496, n_497;
  wire n_498, n_499, n_500, n_501, n_502, n_503, n_504, n_505;
  wire n_506, n_507, n_508, n_509, n_510, n_511;
  xor g1 (Z[0], A[0], B[0]);
  nand g2 (n_98, A[0], B[0]);
  nor g6 (n_99, A[1], B[1]);
  nand g7 (n_102, A[1], B[1]);
  nor g8 (n_109, A[2], B[2]);
  nand g9 (n_104, A[2], B[2]);
  nor g10 (n_105, A[3], B[3]);
  nand g11 (n_106, A[3], B[3]);
  nor g12 (n_115, A[4], B[4]);
  nand g13 (n_110, A[4], B[4]);
  nor g14 (n_111, A[5], B[5]);
  nand g15 (n_112, A[5], B[5]);
  nor g16 (n_121, A[6], B[6]);
  nand g17 (n_116, A[6], B[6]);
  nor g18 (n_117, A[7], B[7]);
  nand g19 (n_118, A[7], B[7]);
  nor g20 (n_127, A[8], B[8]);
  nand g21 (n_122, A[8], B[8]);
  nor g22 (n_123, A[9], B[9]);
  nand g23 (n_124, A[9], B[9]);
  nor g24 (n_133, A[10], B[10]);
  nand g25 (n_128, A[10], B[10]);
  nor g26 (n_129, A[11], B[11]);
  nand g27 (n_130, A[11], B[11]);
  nor g28 (n_139, A[12], B[12]);
  nand g29 (n_134, A[12], B[12]);
  nor g30 (n_135, A[13], B[13]);
  nand g31 (n_136, A[13], B[13]);
  nor g32 (n_145, A[14], B[14]);
  nand g33 (n_140, A[14], B[14]);
  nor g34 (n_141, A[15], B[15]);
  nand g35 (n_142, A[15], B[15]);
  nor g36 (n_151, A[16], B[16]);
  nand g37 (n_146, A[16], B[16]);
  nor g38 (n_147, A[17], B[17]);
  nand g39 (n_148, A[17], B[17]);
  nor g40 (n_157, A[18], B[18]);
  nand g41 (n_152, A[18], B[18]);
  nor g42 (n_153, A[19], B[19]);
  nand g43 (n_154, A[19], B[19]);
  nor g44 (n_163, A[20], B[20]);
  nand g45 (n_158, A[20], B[20]);
  nor g46 (n_159, A[21], B[21]);
  nand g47 (n_160, A[21], B[21]);
  nor g48 (n_169, A[22], B[22]);
  nand g49 (n_164, A[22], B[22]);
  nor g50 (n_165, A[23], B[23]);
  nand g51 (n_166, A[23], B[23]);
  nor g52 (n_175, A[24], B[24]);
  nand g53 (n_170, A[24], B[24]);
  nor g54 (n_171, A[25], B[25]);
  nand g55 (n_172, A[25], B[25]);
  nor g56 (n_181, A[26], B[26]);
  nand g57 (n_176, A[26], B[26]);
  nor g58 (n_177, A[27], B[27]);
  nand g59 (n_178, A[27], B[27]);
  nor g60 (n_187, A[28], B[28]);
  nand g61 (n_182, A[28], B[28]);
  nor g62 (n_183, A[29], B[29]);
  nand g63 (n_184, A[29], B[29]);
  nor g64 (n_193, A[30], B[30]);
  nand g65 (n_188, A[30], B[30]);
  nor g66 (n_189, A[31], B[31]);
  nand g67 (n_190, A[31], B[31]);
  not g68 (n_101, n_99);
  nand g69 (n_103, n_100, n_101);
  nand g70 (n_194, n_102, n_103);
  nor g71 (n_107, n_104, n_105);
  not g72 (n_108, n_106);
  nor g73 (n_198, n_107, n_108);
  nor g74 (n_197, n_109, n_105);
  nor g75 (n_113, n_110, n_111);
  not g76 (n_114, n_112);
  nor g77 (n_200, n_113, n_114);
  nor g78 (n_203, n_115, n_111);
  nor g79 (n_119, n_116, n_117);
  not g80 (n_120, n_118);
  nor g81 (n_207, n_119, n_120);
  nor g82 (n_205, n_121, n_117);
  nor g83 (n_125, n_122, n_123);
  not g84 (n_126, n_124);
  nor g85 (n_210, n_125, n_126);
  nor g86 (n_213, n_127, n_123);
  nor g87 (n_131, n_128, n_129);
  not g88 (n_132, n_130);
  nor g89 (n_217, n_131, n_132);
  nor g90 (n_215, n_133, n_129);
  nor g91 (n_137, n_134, n_135);
  not g92 (n_138, n_136);
  nor g93 (n_220, n_137, n_138);
  nor g94 (n_223, n_139, n_135);
  nor g95 (n_143, n_140, n_141);
  not g96 (n_144, n_142);
  nor g97 (n_227, n_143, n_144);
  nor g98 (n_225, n_145, n_141);
  nor g99 (n_149, n_146, n_147);
  not g100 (n_150, n_148);
  nor g101 (n_230, n_149, n_150);
  nor g102 (n_233, n_151, n_147);
  nor g103 (n_155, n_152, n_153);
  not g104 (n_156, n_154);
  nor g105 (n_237, n_155, n_156);
  nor g106 (n_235, n_157, n_153);
  nor g107 (n_161, n_158, n_159);
  not g108 (n_162, n_160);
  nor g109 (n_240, n_161, n_162);
  nor g110 (n_243, n_163, n_159);
  nor g111 (n_167, n_164, n_165);
  not g112 (n_168, n_166);
  nor g113 (n_247, n_167, n_168);
  nor g114 (n_245, n_169, n_165);
  nor g115 (n_173, n_170, n_171);
  not g116 (n_174, n_172);
  nor g117 (n_250, n_173, n_174);
  nor g118 (n_253, n_175, n_171);
  nor g119 (n_179, n_176, n_177);
  not g120 (n_180, n_178);
  nor g121 (n_257, n_179, n_180);
  nor g122 (n_255, n_181, n_177);
  nor g123 (n_185, n_182, n_183);
  not g124 (n_186, n_184);
  nor g125 (n_260, n_185, n_186);
  nor g126 (n_263, n_187, n_183);
  nor g127 (n_191, n_188, n_189);
  not g128 (n_192, n_190);
  nor g129 (n_267, n_191, n_192);
  nor g130 (n_265, n_193, n_189);
  not g131 (n_195, n_109);
  nand g132 (n_196, n_194, n_195);
  nand g133 (n_440, n_104, n_196);
  nand g134 (n_199, n_197, n_194);
  nand g135 (n_270, n_198, n_199);
  nor g136 (n_201, n_121, n_200);
  not g137 (n_202, n_116);
  nor g138 (n_276, n_201, n_202);
  not g139 (n_204, n_121);
  nand g140 (n_274, n_203, n_204);
  not g141 (n_206, n_205);
  nor g142 (n_208, n_200, n_206);
  not g143 (n_209, n_207);
  nor g144 (n_280, n_208, n_209);
  nand g145 (n_278, n_203, n_205);
  nor g146 (n_211, n_133, n_210);
  not g147 (n_212, n_128);
  nor g148 (n_333, n_211, n_212);
  not g149 (n_214, n_133);
  nand g150 (n_331, n_213, n_214);
  not g151 (n_216, n_215);
  nor g152 (n_218, n_210, n_216);
  not g153 (n_219, n_217);
  nor g154 (n_282, n_218, n_219);
  nand g155 (n_285, n_213, n_215);
  nor g156 (n_221, n_145, n_220);
  not g157 (n_222, n_140);
  nor g158 (n_290, n_221, n_222);
  not g159 (n_224, n_145);
  nand g160 (n_289, n_223, n_224);
  not g161 (n_226, n_225);
  nor g162 (n_228, n_220, n_226);
  not g163 (n_229, n_227);
  nor g164 (n_294, n_228, n_229);
  nand g165 (n_293, n_223, n_225);
  nor g166 (n_231, n_157, n_230);
  not g167 (n_232, n_152);
  nor g168 (n_391, n_231, n_232);
  not g169 (n_234, n_157);
  nand g170 (n_389, n_233, n_234);
  not g171 (n_236, n_235);
  nor g172 (n_238, n_230, n_236);
  not g173 (n_239, n_237);
  nor g174 (n_297, n_238, n_239);
  nand g175 (n_300, n_233, n_235);
  nor g176 (n_241, n_169, n_240);
  not g177 (n_242, n_164);
  nor g178 (n_305, n_241, n_242);
  not g179 (n_244, n_169);
  nand g180 (n_304, n_243, n_244);
  not g181 (n_246, n_245);
  nor g182 (n_248, n_240, n_246);
  not g183 (n_249, n_247);
  nor g184 (n_309, n_248, n_249);
  nand g185 (n_308, n_243, n_245);
  nor g186 (n_251, n_181, n_250);
  not g187 (n_252, n_176);
  nor g188 (n_358, n_251, n_252);
  not g189 (n_254, n_181);
  nand g190 (n_357, n_253, n_254);
  not g191 (n_256, n_255);
  nor g192 (n_258, n_250, n_256);
  not g193 (n_259, n_257);
  nor g194 (n_312, n_258, n_259);
  nand g195 (n_315, n_253, n_255);
  nor g196 (n_261, n_193, n_260);
  not g197 (n_262, n_188);
  nor g198 (n_320, n_261, n_262);
  not g199 (n_264, n_193);
  nand g200 (n_319, n_263, n_264);
  not g201 (n_266, n_265);
  nor g202 (n_268, n_260, n_266);
  not g203 (n_269, n_267);
  nor g204 (n_324, n_268, n_269);
  nand g205 (n_323, n_263, n_265);
  not g206 (n_271, n_115);
  nand g207 (n_272, n_270, n_271);
  nand g208 (n_444, n_110, n_272);
  nand g209 (n_273, n_203, n_270);
  nand g210 (n_446, n_200, n_273);
  not g211 (n_275, n_274);
  nand g212 (n_277, n_270, n_275);
  nand g213 (n_449, n_276, n_277);
  not g214 (n_279, n_278);
  nand g215 (n_281, n_270, n_279);
  nand g216 (n_327, n_280, n_281);
  nor g217 (n_283, n_139, n_282);
  not g218 (n_284, n_134);
  nor g219 (n_338, n_283, n_284);
  nor g220 (n_337, n_139, n_285);
  not g221 (n_286, n_223);
  nor g222 (n_287, n_282, n_286);
  not g223 (n_288, n_220);
  nor g224 (n_341, n_287, n_288);
  nor g225 (n_340, n_285, n_286);
  nor g226 (n_291, n_289, n_282);
  not g227 (n_292, n_290);
  nor g228 (n_344, n_291, n_292);
  nor g229 (n_343, n_285, n_289);
  nor g230 (n_295, n_293, n_282);
  not g231 (n_296, n_294);
  nor g232 (n_347, n_295, n_296);
  nor g233 (n_346, n_285, n_293);
  nor g234 (n_298, n_163, n_297);
  not g235 (n_299, n_158);
  nor g236 (n_396, n_298, n_299);
  nor g237 (n_395, n_163, n_300);
  not g238 (n_301, n_243);
  nor g239 (n_302, n_297, n_301);
  not g240 (n_303, n_240);
  nor g241 (n_399, n_302, n_303);
  nor g242 (n_398, n_300, n_301);
  nor g243 (n_306, n_304, n_297);
  not g244 (n_307, n_305);
  nor g245 (n_402, n_306, n_307);
  nor g246 (n_401, n_300, n_304);
  nor g247 (n_310, n_308, n_297);
  not g248 (n_311, n_309);
  nor g249 (n_349, n_310, n_311);
  nor g250 (n_352, n_300, n_308);
  nor g251 (n_313, n_187, n_312);
  not g252 (n_314, n_182);
  nor g253 (n_367, n_313, n_314);
  nor g254 (n_365, n_187, n_315);
  not g255 (n_316, n_263);
  nor g256 (n_317, n_312, n_316);
  not g257 (n_318, n_260);
  nor g258 (n_372, n_317, n_318);
  nor g259 (n_370, n_315, n_316);
  nor g260 (n_321, n_319, n_312);
  not g261 (n_322, n_320);
  nor g262 (n_377, n_321, n_322);
  nor g263 (n_375, n_315, n_319);
  nor g264 (n_325, n_323, n_312);
  not g265 (n_326, n_324);
  nor g266 (n_382, n_325, n_326);
  nor g267 (n_380, n_315, n_323);
  not g268 (n_328, n_127);
  nand g269 (n_329, n_327, n_328);
  nand g270 (n_453, n_122, n_329);
  nand g271 (n_330, n_213, n_327);
  nand g272 (n_455, n_210, n_330);
  not g273 (n_332, n_331);
  nand g274 (n_334, n_327, n_332);
  nand g275 (n_458, n_333, n_334);
  not g276 (n_335, n_285);
  nand g277 (n_336, n_327, n_335);
  nand g278 (n_461, n_282, n_336);
  nand g279 (n_339, n_337, n_327);
  nand g280 (n_464, n_338, n_339);
  nand g281 (n_342, n_340, n_327);
  nand g282 (n_466, n_341, n_342);
  nand g283 (n_345, n_343, n_327);
  nand g284 (n_469, n_344, n_345);
  nand g285 (n_348, n_346, n_327);
  nand g286 (n_385, n_347, n_348);
  nor g287 (n_350, n_175, n_349);
  not g288 (n_351, n_170);
  nor g289 (n_407, n_350, n_351);
  not g290 (n_353, n_175);
  nand g291 (n_405, n_352, n_353);
  not g292 (n_354, n_253);
  nor g293 (n_355, n_349, n_354);
  not g294 (n_356, n_250);
  nor g295 (n_411, n_355, n_356);
  nand g296 (n_409, n_253, n_352);
  nor g297 (n_359, n_357, n_349);
  not g298 (n_360, n_358);
  nor g299 (n_415, n_359, n_360);
  not g300 (n_361, n_357);
  nand g301 (n_413, n_352, n_361);
  nor g302 (n_362, n_315, n_349);
  not g303 (n_363, n_312);
  nor g304 (n_419, n_362, n_363);
  not g305 (n_364, n_315);
  nand g306 (n_417, n_352, n_364);
  not g307 (n_366, n_365);
  nor g308 (n_368, n_349, n_366);
  not g309 (n_369, n_367);
  nor g310 (n_423, n_368, n_369);
  nand g311 (n_421, n_352, n_365);
  not g312 (n_371, n_370);
  nor g313 (n_373, n_349, n_371);
  not g314 (n_374, n_372);
  nor g315 (n_427, n_373, n_374);
  nand g316 (n_425, n_352, n_370);
  not g317 (n_376, n_375);
  nor g318 (n_378, n_349, n_376);
  not g319 (n_379, n_377);
  nor g320 (n_431, n_378, n_379);
  nand g321 (n_429, n_352, n_375);
  not g322 (n_381, n_380);
  nor g323 (n_383, n_349, n_381);
  not g324 (n_384, n_382);
  nor g325 (n_435, n_383, n_384);
  nand g326 (n_433, n_352, n_380);
  not g327 (n_386, n_151);
  nand g328 (n_387, n_385, n_386);
  nand g329 (n_473, n_146, n_387);
  nand g330 (n_388, n_233, n_385);
  nand g331 (n_475, n_230, n_388);
  not g332 (n_390, n_389);
  nand g333 (n_392, n_385, n_390);
  nand g334 (n_478, n_391, n_392);
  not g335 (n_393, n_300);
  nand g336 (n_394, n_385, n_393);
  nand g337 (n_481, n_297, n_394);
  nand g338 (n_397, n_395, n_385);
  nand g339 (n_484, n_396, n_397);
  nand g340 (n_400, n_398, n_385);
  nand g341 (n_486, n_399, n_400);
  nand g342 (n_403, n_401, n_385);
  nand g343 (n_489, n_402, n_403);
  nand g344 (n_404, n_352, n_385);
  nand g345 (n_491, n_349, n_404);
  not g346 (n_406, n_405);
  nand g347 (n_408, n_385, n_406);
  nand g348 (n_494, n_407, n_408);
  not g349 (n_410, n_409);
  nand g350 (n_412, n_385, n_410);
  nand g351 (n_496, n_411, n_412);
  not g352 (n_414, n_413);
  nand g353 (n_416, n_385, n_414);
  nand g354 (n_499, n_415, n_416);
  not g355 (n_418, n_417);
  nand g356 (n_420, n_385, n_418);
  nand g357 (n_502, n_419, n_420);
  not g358 (n_422, n_421);
  nand g359 (n_424, n_385, n_422);
  nand g360 (n_505, n_423, n_424);
  not g361 (n_426, n_425);
  nand g362 (n_428, n_385, n_426);
  nand g363 (n_507, n_427, n_428);
  not g364 (n_430, n_429);
  nand g365 (n_432, n_385, n_430);
  nand g366 (n_510, n_431, n_432);
  not g367 (n_434, n_433);
  nand g368 (n_436, n_385, n_434);
  nand g369 (Z[32], n_435, n_436);
  nand g370 (n_437, n_101, n_102);
  xnor g371 (Z[1], n_100, n_437);
  nand g372 (n_438, n_195, n_104);
  xnor g373 (Z[2], n_194, n_438);
  not g374 (n_439, n_105);
  nand g375 (n_441, n_439, n_106);
  xnor g376 (Z[3], n_440, n_441);
  nand g377 (n_442, n_271, n_110);
  xnor g378 (Z[4], n_270, n_442);
  not g379 (n_443, n_111);
  nand g380 (n_445, n_443, n_112);
  xnor g381 (Z[5], n_444, n_445);
  nand g382 (n_447, n_204, n_116);
  xnor g383 (Z[6], n_446, n_447);
  not g384 (n_448, n_117);
  nand g385 (n_450, n_448, n_118);
  xnor g386 (Z[7], n_449, n_450);
  nand g387 (n_451, n_328, n_122);
  xnor g388 (Z[8], n_327, n_451);
  not g389 (n_452, n_123);
  nand g390 (n_454, n_452, n_124);
  xnor g391 (Z[9], n_453, n_454);
  nand g392 (n_456, n_214, n_128);
  xnor g393 (Z[10], n_455, n_456);
  not g394 (n_457, n_129);
  nand g395 (n_459, n_457, n_130);
  xnor g396 (Z[11], n_458, n_459);
  not g397 (n_460, n_139);
  nand g398 (n_462, n_460, n_134);
  xnor g399 (Z[12], n_461, n_462);
  not g400 (n_463, n_135);
  nand g401 (n_465, n_463, n_136);
  xnor g402 (Z[13], n_464, n_465);
  nand g403 (n_467, n_224, n_140);
  xnor g404 (Z[14], n_466, n_467);
  not g405 (n_468, n_141);
  nand g406 (n_470, n_468, n_142);
  xnor g407 (Z[15], n_469, n_470);
  nand g408 (n_471, n_386, n_146);
  xnor g409 (Z[16], n_385, n_471);
  not g410 (n_472, n_147);
  nand g411 (n_474, n_472, n_148);
  xnor g412 (Z[17], n_473, n_474);
  nand g413 (n_476, n_234, n_152);
  xnor g414 (Z[18], n_475, n_476);
  not g415 (n_477, n_153);
  nand g416 (n_479, n_477, n_154);
  xnor g417 (Z[19], n_478, n_479);
  not g418 (n_480, n_163);
  nand g419 (n_482, n_480, n_158);
  xnor g420 (Z[20], n_481, n_482);
  not g421 (n_483, n_159);
  nand g422 (n_485, n_483, n_160);
  xnor g423 (Z[21], n_484, n_485);
  nand g424 (n_487, n_244, n_164);
  xnor g425 (Z[22], n_486, n_487);
  not g426 (n_488, n_165);
  nand g427 (n_490, n_488, n_166);
  xnor g428 (Z[23], n_489, n_490);
  nand g429 (n_492, n_353, n_170);
  xnor g430 (Z[24], n_491, n_492);
  not g431 (n_493, n_171);
  nand g432 (n_495, n_493, n_172);
  xnor g433 (Z[25], n_494, n_495);
  nand g434 (n_497, n_254, n_176);
  xnor g435 (Z[26], n_496, n_497);
  not g436 (n_498, n_177);
  nand g437 (n_500, n_498, n_178);
  xnor g438 (Z[27], n_499, n_500);
  not g439 (n_501, n_187);
  nand g440 (n_503, n_501, n_182);
  xnor g441 (Z[28], n_502, n_503);
  not g442 (n_504, n_183);
  nand g443 (n_506, n_504, n_184);
  xnor g444 (Z[29], n_505, n_506);
  nand g445 (n_508, n_264, n_188);
  xnor g446 (Z[30], n_507, n_508);
  not g447 (n_509, n_189);
  nand g448 (n_511, n_509, n_190);
  xnor g449 (Z[31], n_510, n_511);
  not g451 (n_100, n_98);
endmodule

module add32(clk, a, b, sum);
  input clk;
  input [31:0] a, b;
  output [32:0] sum;
  wire clk;
  wire [31:0] a, b;
  wire [32:0] sum;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34;
  add_unsigned add_9_6(.A (a), .B (b), .Z ({n_34, n_33, n_32, n_31,
       n_30, n_29, n_28, n_27, n_26, n_25, n_24, n_23, n_22, n_21,
       n_20, n_19, n_18, n_17, n_16, n_15, n_14, n_13, n_12, n_11,
       n_10, n_9, n_8, n_7, n_6, n_5, n_4, n_3, n_2}));
  CDN_flop \sum_reg[0] (.clk (clk), .d (n_2), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[0]));
  CDN_flop \sum_reg[1] (.clk (clk), .d (n_3), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[1]));
  CDN_flop \sum_reg[2] (.clk (clk), .d (n_4), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[2]));
  CDN_flop \sum_reg[3] (.clk (clk), .d (n_5), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[3]));
  CDN_flop \sum_reg[4] (.clk (clk), .d (n_6), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[4]));
  CDN_flop \sum_reg[5] (.clk (clk), .d (n_7), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[5]));
  CDN_flop \sum_reg[6] (.clk (clk), .d (n_8), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[6]));
  CDN_flop \sum_reg[7] (.clk (clk), .d (n_9), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[7]));
  CDN_flop \sum_reg[8] (.clk (clk), .d (n_10), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[8]));
  CDN_flop \sum_reg[9] (.clk (clk), .d (n_11), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[9]));
  CDN_flop \sum_reg[10] (.clk (clk), .d (n_12), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[10]));
  CDN_flop \sum_reg[11] (.clk (clk), .d (n_13), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[11]));
  CDN_flop \sum_reg[12] (.clk (clk), .d (n_14), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[12]));
  CDN_flop \sum_reg[13] (.clk (clk), .d (n_15), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[13]));
  CDN_flop \sum_reg[14] (.clk (clk), .d (n_16), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[14]));
  CDN_flop \sum_reg[15] (.clk (clk), .d (n_17), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[15]));
  CDN_flop \sum_reg[16] (.clk (clk), .d (n_18), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[16]));
  CDN_flop \sum_reg[17] (.clk (clk), .d (n_19), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[17]));
  CDN_flop \sum_reg[18] (.clk (clk), .d (n_20), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[18]));
  CDN_flop \sum_reg[19] (.clk (clk), .d (n_21), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[19]));
  CDN_flop \sum_reg[20] (.clk (clk), .d (n_22), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[20]));
  CDN_flop \sum_reg[21] (.clk (clk), .d (n_23), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[21]));
  CDN_flop \sum_reg[22] (.clk (clk), .d (n_24), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[22]));
  CDN_flop \sum_reg[23] (.clk (clk), .d (n_25), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[23]));
  CDN_flop \sum_reg[24] (.clk (clk), .d (n_26), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[24]));
  CDN_flop \sum_reg[25] (.clk (clk), .d (n_27), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[25]));
  CDN_flop \sum_reg[26] (.clk (clk), .d (n_28), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[26]));
  CDN_flop \sum_reg[27] (.clk (clk), .d (n_29), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[27]));
  CDN_flop \sum_reg[28] (.clk (clk), .d (n_30), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[28]));
  CDN_flop \sum_reg[29] (.clk (clk), .d (n_31), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[29]));
  CDN_flop \sum_reg[30] (.clk (clk), .d (n_32), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[30]));
  CDN_flop \sum_reg[31] (.clk (clk), .d (n_33), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[31]));
  CDN_flop \sum_reg[32] (.clk (clk), .d (n_34), .sena (1'b1), .aclr
       (1'b0), .apre (1'b0), .srl (1'b0), .srd (1'b0), .q (sum[32]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif

Instance: /add32
Power Unit: W
PDB Frames: /stim#0/frame#0
  -------------------------------------------------------------------------
    Category         Leakage     Internal    Switching        Total    Row%
  -------------------------------------------------------------------------
      memory     0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00   0.00%
    register     1.37301e-08  8.01302e-06  0.00000e+00  8.02675e-06  35.73%
       latch     0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00   0.00%
       logic     1.85774e-08  1.44181e-05  0.00000e+00  1.44367e-05  64.27%
        bbox     0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00   0.00%
       clock     0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00   0.00%
         pad     0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00   0.00%
          pm     0.00000e+00  0.00000e+00  0.00000e+00  0.00000e+00   0.00%
  -------------------------------------------------------------------------
    Subtotal     3.23075e-08  2.24311e-05  0.00000e+00  2.24634e-05 100.00%
  Percentage           0.14%       99.86%        0.00%      100.00% 100.00%
  -------------------------------------------------------------------------

# Cadence Genus(TM) Synthesis Solution, Version 21.14-s082_1, built Jun 23 2022 14:32:08

# Date: Wed Sep 24 09:38:40 2025
# Host: PG-VLSI07 (x86_64 w/Linux 4.18.0-425.3.1.el8.x86_64) (12cores*20cpus*1physical cpu*12th Gen Intel(R) Core(TM) i7-12700 25600KB)
# OS:   Red Hat Enterprise Linux release 8.7 (Ootpa)

set_db /  .init_lib_search_path
set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}
set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}

# Cadence Genus(TM) Synthesis Solution, Version 21.14-s082_1, built Jun 23 2022 14:32:08

# Date: Wed Sep 24 09:47:45 2025
# Host: PG-VLSI07 (x86_64 w/Linux 4.18.0-425.3.1.el8.x86_64) (12cores*20cpus*1physical cpu*12th Gen Intel(R) Core(TM) i7-12700 25600KB)
# OS:   Red Hat Enterprise Linux release 8.7 (Ootpa)

set_db /  .init_lib_search_path{/home/install/FOUNDRY/digital/45nm/dig/lib}
set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}
set_db /  .init_lib_search_path{ /home/ install/FOUNDRY/digital/45nm/dig/lib}
set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}
set_db /  .init_lib_search_path {/home/ install/FOUNDRY/digital/45nm/dig/lib}
set_db /  .library "typical.lib"
set_db /\ .library "typical.lib"
set_db /\.library "typical.lib"
set_db/\.library "typical.lib"
set_db\.library "typical.lib"
set_db/.library "typical.lib"
set_db/ .library "typical.lib"
set_db /.library "typical.lib"
set_db/ .library "typical.lib"
reaf_hdl "add32.v"
read_hdl "add32.v"
elaborate add32
elaborate add32
set_db / .library "typical.lib"
set_db / .init_lib_search_path {/home/install/FOUNDRY/digital/45nm/dig/lib}
set_db / .library "typical.lib"
read_hdl "add32.v"
elaborate add32
report timing -unconstrained>add32_timing.rpt
report power>add32_power.rpt
report timing -unconstrained>add32_timing.rpt
report power > add32_power.rpt
report area > add32_area.rpt
write_hdl > add32_netlist.v
gui_show

Cadence Genus(TM) Synthesis Solution.
Copyright 2022 Cadence Design Systems, Inc. All rights reserved worldwide.
Cadence and the Cadence logo are registered trademarks and Genus is a trademark
of Cadence Design Systems, Inc. in the United States and other countries.

[09:38:40.064449] Configured Lic search path (21.01-s002): 5280@172.1.13.56

Version: 21.14-s082_1, built Thu Jun 23 02:02:08 PDT 2022
Options: 
Date:    Wed Sep 24 09:38:40 2025
Host:    PG-VLSI07 (x86_64 w/Linux 4.18.0-425.3.1.el8.x86_64) (12cores*20cpus*1physical cpu*12th Gen Intel(R) Core(TM) i7-12700 25600KB) (15870532KB)
PID:     7606
OS:      Red Hat Enterprise Linux release 8.7 (Ootpa)


[09:38:40.229624] periodic Lic check successful
[09:38:40.229625] Feature usage summary:
[09:38:40.229625] Genus_Synthesis
Checking out license: Genus_Synthesis


***********************************************************************************************************
***********************************************************************************************************



Loading tool scripts...
Finished loading tool scripts (3 seconds elapsed).

WARNING: This version of the tool is 1188 days old.
@genus:root: 1> set_db /  .init_lib_search_path
Error   : Argument 'value' is required for command 'set_db'. [TUI-192] [set_db]
        : Argument 'value' is required for command 'set_db'.
        : Refer to the Command Reference for details.
1

Another Ctrl-C within 1 second will terminate the tool.
CURRENT RESOURCES: RT {elapsed: 142s, ST: 6s, FG: 6s, CPU: 3.9%}, MEM {curr: 1.0G, peak: 1.0G, phys curr: 0.3G, phys peak: 0.3G}, SYS {load: 0.0, cpu: 20, total: 15.1G, free: 11.6G}

Another Ctrl-C within 1 second will terminate the tool.
CURRENT RESOURCES: RT {elapsed: 157s, ST: 6s, FG: 6s, CPU: 3.9%}, MEM {curr: 1.0G, peak: 1.0G, phys curr: 0.3G, phys peak: 0.3G}, SYS {load: 0.0, cpu: 20, total: 15.1G, free: 11.6G}

Another Ctrl-C within 1 second will terminate the tool.
CURRENT RESOURCES: RT {elapsed: 158s, ST: 6s, FG: 6s, CPU: 3.9%}, MEM {curr: 1.0G, peak: 1.0G, phys curr: 0.3G, phys peak: 0.3G}, SYS {load: 0.0, cpu: 20, total: 15.1G, free: 11.6G}
@genus:root: 2> 
@genus:root: 2> set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}
Error   : Unrecognized attribute. [TUI-183] [set_db]
        : 'init_lib_search_path{/home/' is not a recognized attribute for object 'root'.
        : To see the usage/description for this attribute, type 'help * <attr_name> -detail'.
1
@genus:root: 3> set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}
Error   : Unrecognized attribute. [TUI-183] [set_db]
        : 'init_lib_search_path{/home/' is not a recognized attribute for object 'root'.
1

Cadence Genus(TM) Synthesis Solution.
Copyright 2022 Cadence Design Systems, Inc. All rights reserved worldwide.
Cadence and the Cadence logo are registered trademarks and Genus is a trademark
of Cadence Design Systems, Inc. in the United States and other countries.

[09:47:45.064489] Configured Lic search path (21.01-s002): 5280@172.1.13.56

Version: 21.14-s082_1, built Thu Jun 23 02:02:08 PDT 2022
Options: 
Date:    Wed Sep 24 09:47:45 2025
Host:    PG-VLSI07 (x86_64 w/Linux 4.18.0-425.3.1.el8.x86_64) (12cores*20cpus*1physical cpu*12th Gen Intel(R) Core(TM) i7-12700 25600KB) (15870532KB)
PID:     8092
OS:      Red Hat Enterprise Linux release 8.7 (Ootpa)


[09:47:45.016472] Periodic Lic check successful
[09:47:45.016480] Feature usage summary:
[09:47:45.016481] Genus_Synthesis
Checking out license: Genus_Synthesis


***********************************************************************************************************
***********************************************************************************************************



Loading tool scripts...
Finished loading tool scripts (4 seconds elapsed).

WARNING: This version of the tool is 1188 days old.
@genus:root: 1> set_db /  .init_lib_search_path{/home/install/FOUNDRY/digital/45nm/dig/lib}
Error   : Argument 'value' is required for command 'set_db'. [TUI-192] [set_db]
        : Argument 'value' is required for command 'set_db'.
        : Refer to the Command Reference for details.
1
@genus:root: 2> set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}
Error   : Unrecognized attribute. [TUI-183] [set_db]
        : 'init_lib_search_path{/home/' is not a recognized attribute for object 'root'.
        : To see the usage/description for this attribute, type 'help * <attr_name> -detail'.
1
@genus:root: 3> set_db /  .init_lib_search_path{ /home/ install/FOUNDRY/digital/45nm/dig/lib}
Error   : A command argument did not match any of the acceptable command options. [TUI-64] [set_db]
        : The argument in question is 'install/FOUNDRY/digital/45nm/dig/lib}'.
        : Check the command usage and correct the input to the command.
  set_db: set attributes on objects 

Usage: set_db [-quiet] [-verbose] [-dbu] [-index <string>] <string> <string>
           [<string>]

    [-quiet]:
        keeps quiet unless there are problems 
    [-verbose]:
        enables verbose 
    [-dbu]:
        indicates that attribute (coord, pt, rect, polygon, area, etc.) will be 
        in database units 
    [-index <string>]:
        list of indices in a form of pairs of index_name value or a object name 
    <string>:
        <start> can be any object list (or collection) or <shorthand> (e.g., 
        nets, insts, etc) 
    <string>:
        the <chain> is in the form [.<attribute_name1>[.<attribute_name2>]...] 
    [<string>]:
        the attribute value 
1
@genus:root: 4> set_db /  .init_lib_search_path{/home/ install/FOUNDRY/digital/45nm/dig/lib}
Error   : Unrecognized attribute. [TUI-183] [set_db]
        : 'init_lib_search_path{/home/' is not a recognized attribute for object 'root'.
1
@genus:root: 5> set_db /  .init_lib_search_path {/home/ install/FOUNDRY/digital/45nm/dig/lib}
  Setting attribute of root '/': 'init_lib_search_path' = /home/ install/FOUNDRY/digital/45nm/dig/lib
1 {/home/ install/FOUNDRY/digital/45nm/dig/lib}
@genus:root: 6> set_db /  .library "typical.lib"
Error   : File error. [FILE-100] [set_db]
        : Cannot open file 'typical.lib'
        : Make sure that the file is a readable regular file and has the specified name.
Error   : A library file does not exist. [LBR-68] [set_db]
        : File 'typical.lib' could not be found. File '<none>' was the last file that was successfully read in.
        : Make sure that the library file exists or check for a typo in the file name.
Error   : The data value for this attribute is invalid. [TUI-24] [set_db]
        : The value 'typical.lib' cannot be set for attribute 'library'.
        : To see the usage/description for this attribute, type '::legacy::set_attribute -h <attr_name> *' (in legacy UI mode) or 'help * <attr_name> -detail' (in CUI mode).
1
@genus:root: 7> set_db /\ .library "typical.lib"
Error   : Argument 'value' is required for command 'set_db'. [TUI-192] [set_db]
        : Argument 'value' is required for command 'set_db'.
1
@genus:root: 8> set_db /\.library "typical.lib"
Error   : <Start> word is not recognized. [TUI-182] [set_db]
        : '/.library' is not a recognized object/attribute. Type 'help root:' to get a list of all supported objects and attributes.
        : Check if the given <Start> word is a valid object_type, object or attribute.
1
@genus:root: 9> set_db/\.library "typical.lib"
invalid command name "set_db/.library"
@genus:root: 10> set_db\.library "typical.lib"
invalid command name "set_db.library"
@genus:root: 11> set_db/.library "typical.lib"
invalid command name "set_db/.library"
@genus:root: 12> set_db/ .library "typical.lib"
invalid command name "set_db/"
@genus:root: 13> set_db /.library "typical.lib"
Error   : <Start> word is not recognized. [TUI-182] [set_db]
        : '/.library' is not a recognized object/attribute. Type 'help root:' to get a list of all supported objects and attributes.
1
@genus:root: 14> set_db/ .library "typical.lib"
invalid command name "set_db/"
@genus:root: 15> reaf_hdl "add32.v"
invalid command name "reaf_hdl"
@genus:root: 16> read_hdl "add32.v"
@genus:root: 17> elaborate add32
Error   : Failed to execute command. [LBR-163] [elaborate]
        : No target technology library was loaded.
        : Specify libraries using read_libs or read_mmmc.
UM:   flow.cputime  flow.realtime  timing.setup.tns  timing.setup.wns  snapshot
UM:*                                                                   elaborate
1
@genus:root: 18> elaborate add32
Error   : Failed to execute command. [LBR-163] [elaborate]
        : No target technology library was loaded.
      flow.cputime  flow.realtime  timing.setup.tns  timing.setup.wns  snapshot
UM:*                                                                   elaborate
1
@genus:root: 19> set_db / .library "typical.lib"
Error   : File error. [FILE-100] [set_db]
        : Cannot open file 'typical.lib'
Error   : A library file does not exist. [LBR-68] [set_db]
        : File 'typical.lib' could not be found. File '<none>' was the last file that was successfully read in.
Error   : The data value for this attribute is invalid. [TUI-24] [set_db]
        : The value 'typical.lib' cannot be set for attribute 'library'.
1
@genus:root: 20> set_db / .init_lib_search_path {/home/install/FOUNDRY/digital/45nm/dig/lib}
  Setting attribute of root '/': 'init_lib_search_path' = /home/install/FOUNDRY/digital/45nm/dig/lib
1 /home/install/FOUNDRY/digital/45nm/dig/lib
@genus:root: 21> set_db / .library "typical.lib"

Threads Configured:3

  Message Summary for Library typical.lib:
  ****************************************
  Missing a function attribute in the output pin definition. [LBR-518]: 1
  Missing library level attribute. [LBR-516]: 1
  ****************************************
 
Info    : Created nominal operating condition. [LBR-412]
        : Operating condition '_nominal_' was created for the PVT values (1.000000, 1.200000, 25.000000) in library 'typical.lib'.
        : The nominal operating condition is represented, either by the nominal PVT values specified in the library source (via nom_process,nom_voltage and nom_temperature respectively), or by the default PVT values (1.0,1.0,1.0).
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/ADDFHX2'.
        : Specify a valid area value for the libcell.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/ADDFHX4'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/ADDFHXL'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/ADDFXL'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/ADDHX2'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/ADDHXL'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND2X4'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND2X6'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND2XL'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND3X1'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND3X8'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND3XL'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND4X1'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND4X4'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND4X8'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AND4XL'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AO21X1'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AO21X2'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AO21XL'.
Warning : Libcell has no area attribute.  Defaulting to 0 area. [LBR-43]
        : Assigning 0 area to library cell 'typical/AO22X1'.
Warning : Maximum message print count reached. [MESG-11]
        : Maximum print count of '20' reached for message 'LBR-43'.
  Setting attribute of root '/': 'library' = typical.lib
1 typical.lib
@genus:root: 22> read_hdl "add32.v"
module add32(clk,a,b,sum);
           |
Warning : Replacing previously read Verilog description. [VLOGPT-6]
        : Replacing Verilog description 'add32' with Verilog module in file 'add32.v' on line 1, column 12.
        : A Verilog description is replaced when a new description of the same name and same library is read again.
    Verilog descriptions are:
       module
       macromodule
       configuration
    SystemVerilog adds the following descriptions:
       interface
       program
       package.
Warning : Replacing previously read Verilog module or VHDL entity. [HPT-76]
        : Replacing Verilog module 'add32' in library 'default' with newly read Verilog module 'add32' in the same library in file 'add32.v' on line 1.
        : A newly read VHDL entity replaces any previously read Verilog module or VHDL entity in the same library if its name matches (case-insensitively) the existing module or entity.
    For instance:
        VHDL 'foo'                  replaces  VHDL {'FOO' or 'foo' or 'Foo' or ...} in the same library
        VHDL 'foo' (in any library) replaces  Verilog {'FOO' or 'foo' or 'Foo' or ...} in the same library
 
A newly read Verilog module replaces any previously read Verilog module if its name matches (case-sensitively) that module.  Further, it replaces any previously read VHDL entity in the same library if its name matches (case -insensitively) that entity.
    For instance:
        Verilog 'foo' replaces    VHDL {'FOO' or 'foo' or 'Foo' or ...} in the same library
        Verilog 'foo' replaces    Verilog 'foo' only
    In addition:
        Verilog 'foo' does not replace Verilog 'FOO' and the two remain as distinct modules.
@genus:root: 23> elaborate add32
  Library has 324 usable logic and 126 usable sequential lib-cells.
Info    : Elaborating Design. [ELAB-1]
        : Elaborating top-level block 'add32' from file 'add32.v'.
Info    : Done Elaborating Design. [ELAB-3]
        : Done elaborating 'add32'.
Checking for analog nets...
Check completed for analog nets.
Checking for source RTL...
Check completed for source RTL.
Running Unified Mux Engine Tricks...
Completed Unified Mux Engine Tricks

Stage: post_elab
--------------------------------------------------------
| Trick             | Accepts | Rejects | Runtime (ms) | 
--------------------------------------------------------
| ume_constant_bmux |       0 |       0 |         0.00 | 
--------------------------------------------------------
Starting clip mux common data inputs [v1.0] (stage: post_elab, startdef: add32, recur: true)
Completed clip mux common data inputs (accepts: 0, rejects: 0, runtime: 0.000s)
Starting clip the non-user hierarchies [v2.0] (stage: post_elab, startdef: add32, recur: true)
Completed clip the non-user hierarchies (accepts: 0, rejects: 0, runtime: 0.000s)

Stage: post_elab
---------------------------------------------------------
| Transform          | Accepts | Rejects | Runtime (ms) | 
---------------------------------------------------------
| hlo_clip_mux_input |       0 |       0 |         0.00 | 
| hlo_clip           |       0 |       0 |         0.00 | 
---------------------------------------------------------
      flow.cputime  flow.realtime  timing.setup.tns  timing.setup.wns  snapshot
UM:*                                                                   elaborate
design:add32
@genus:root: 24> report timing -unconstrained>add32_timing.rpt
Error   : An invalid option was specified. [TUI-204] [_report_timing]
        : An option named '-unconstrained>add32_timing.rpt' could not be found.
        : Run 'command_name -help' to check all valid options. To correct the option and rerun the command.
  _report_timing: prints a timing report 

Usage: _report_timing [-fields <string>] [-output_format <string>]
           [-path_type <string>] [-split_delay] [-stage_delay] [-hpins] [-nets]
           [-exception_data] [-unconstrained] [-physical] [-user_derate]
           [-user_mean_derate] [-user_sigma_derate] [-incr_derate] [-gui]
           [-max_paths <integer>] [-nworst <integer>] [-logic_levels <integer>]
           [-skip_buf] [-skip_inv] [-logic_levels_tcl_list] [-max_slack <float>]
           [-min_slack <float>] [-paths <string>] [-domain <clock_domain>]
           [-views <analysis_view>+] [-collection]
           [ -from <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -from_rise <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -from_fall <inst|hinst|external_delay|clock|port|pin|hpin>+ ]
           [ -through <inst|hinst|hnet|port|pin|hpin>+ |
             -through_rise <inst|hinst|hnet|port|pin|hpin>+ |
             -through_fall <inst|hinst|hnet|port|pin|hpin>+ ]+
           [ -not_through <inst|hinst|hnet|port|pin|hpin>+ |
             -not_through_rise <inst|hinst|hnet|port|pin|hpin>+ |
             -not_through_fall <inst|hinst|hnet|port|pin|hpin>+ ]
           [ -to <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -to_rise <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -to_fall <inst|hinst|external_delay|clock|port|pin|hpin>+ ]
           [ -capture_clock_pins <pin|hpin>+ |
             -capture_clock_pins_rise_clock <pin|hpin>+ |
             -capture_clock_pins_fall_clock <pin|hpin>+ |
             -capture_clock_pins_rise_pin <pin|hpin>+ |
             -capture_clock_pins_fall_pin <pin|hpin>+ ]
           [-exceptions <exception>+] [-group <cost_group>+]
           [-timing_bin <timing_bin>] [-timing_path <timing_bin_path>]
           [<timing_path>+] [> file]

    [-fields <string>]:
        fields 
    [-output_format <string>]:
        supported output format types are <gtd|text> 
    [-path_type <string>]:
        supported path types are <full|summary|full_clock|endpoint> 
    [-split_delay]:
        displays both drivers and loads in the data path 
    [-stage_delay]:
        displays only drivers in the data path 
    [-hpins]:
        displays hierarchical pins in the data path 
    [-nets]:
        displays nets in the data path 
    [-exception_data]:
        displays the exception cross-linking information 
    [-unconstrained]:
        displays the unconstrained paths 
    [-physical]:
        include physical information in report 
    [-user_derate]:
        show 'user_derate' column in timing reports 
    [-user_mean_derate]:
        show 'user_mean_derate' column in timing reports 
    [-user_sigma_derate]:
        show 'user_sigma_derate' column in timing reports 
    [-incr_derate]:
        show 'incr_derate' column in timing reports 
    [-gui]:
        invoke GUI timing report dialog 
    [-max_paths <integer>]:
        number of paths 
    [-nworst <integer>]:
        number of worst paths to each endpoint (inapplicable to path_type 
        endpoint) 
    [-logic_levels <integer>]:
        number of paths to report in the output 
    [-skip_buf]:
        skip buffers when computing logic levels 
    [-skip_inv]:
        skip inverters when computing logic levels 
    [-logic_levels_tcl_list]:
        list output 
    [-max_slack <float>]:
        only paths with less than this slack 
    [-min_slack <float>]:
        only paths with greater than this slack 
    [-paths <string>]:
        a path identifier result from the specify_paths command 
    [-domain <clock_domain>]:
        a clock domain the paths should be restricted to 
    [-views <analysis_view>+]:
        a view the paths should be restricted to 
    [-collection]:
        return a collection of timing paths 
    -from <inst|hinst|external_delay|clock|port|pin|hpin>+:
        a set of startpoints for the paths 
    -from_rise <inst|hinst|external_delay|clock|port|pin|hpin>+:
        startpoints with a rise transition at the pin itself 
    -from_fall <inst|hinst|external_delay|clock|port|pin|hpin>+:
        startpoints with a fall transition at the pin itself 
    -through <inst|hinst|hnet|port|pin|hpin>+:
        specifies paths that pass through these pins or instances. This option 
        can be repeated indicating that the path must go through at least one 
        element of each through list (in the order the options were specified). 
        Objects must be ports, hierarchical pins, pins on sequential/mapped 
        combinational cells, or sequential/mapped combinational instances 
    -through_rise <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that contain a rise transition in one of 
        these objects and it can be repeated and can be combined with -through 
        and/or -through_fall_pin 
    -through_fall <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that contain a fall transition in one of 
        these objects and it can be repeated and can be combined with -through 
        and/or -through_rise_pin 
    -not_through <inst|hinst|hnet|port|pin|hpin>+:
        specifies paths that do not pass through these pins or instances. 
        Objects must be ports, hierarchical pins, pins on sequential/mapped 
        combinational cells, or sequential/mapped combinational instances 
    -not_through_rise <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that does not contain a rise transition in 
        one of these objects 
    -not_through_fall <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that does not contain a fall transition in 
        one of these objects 
    -to <inst|hinst|external_delay|clock|port|pin|hpin>+:
        a set of endpoints for the paths 
    -to_rise <inst|hinst|external_delay|clock|port|pin|hpin>+:
        endpoints with a rise transition at the pin itself 
    -to_fall <inst|hinst|external_delay|clock|port|pin|hpin>+:
        endpoints with a fall transition at the pin itself 
    -capture_clock_pins <pin|hpin>+:
        sequential clock pins at the path endpoint 
    -capture_clock_pins_rise_clock <pin|hpin>+:
        pins that capture with rising clock edge 
    -capture_clock_pins_fall_clock <pin|hpin>+:
        pins that capture with falling clock edge 
    -capture_clock_pins_rise_pin <pin|hpin>+:
        pins that capture with rise transition at the pin itself 
    -capture_clock_pins_fall_pin <pin|hpin>+:
        pins that capture with fall transition at the pin itself 
    [-exceptions <exception>+]:
        report paths for exceptions 
    [-group <cost_group>+]:
        report paths for the specified cost groups/path groups 
    [-timing_bin <timing_bin>]:
        timing bin to report 
    [-timing_path <timing_bin_path>]:
        timing path to report 
    [<timing_path>+]:
        path_collection 
Fields presented are controlled by the '-fields' switch or the attribute
'timing_report_fields' and 'timing_report_endpoint_fields'
Valid full report fields are:
  - timing_point:        names of pins
  - flags:               flags associated with the column timing_point
  - arc:                 timing arc for which timing information was applied
  - edge:                rising/falling edge
  - cell:                cell type, exception type, etc.
  - fanout:              fanout of leaf cells
  - load:                load of leaf cells
  - transition:          slew of leaf cell outputs
  - transition_mean:     mean slew of leaf cell outputs
  - transition_sigma:    sigma slew of leaf cell outputs
  - delay:               delay through a leaf cell
  - delay_mean:          mean delay through a leaf cell
  - delay_sigma:         sigma delay through a leaf cell
  - arrival:             arrival time at a leaf cell
  - arrival_mean:        mean arrival time at a leaf cell
  - arrival_sigma:       sigma arrival time at a leaf cell
  - lib_set:             display the library set of the cell
  - user_derate:         derating information
  - user_mean_derate:    mean derating information
  - user_sigma_derate:   derating information
  - total_derate:        total derating information
  - incr_derate:        incr derating information
  - aocv_derate:         aocv derating information
  - socv_derate:         socv spatial derating information
  - stage_count:         aocv stage depth
  - power_domain:        power domain associated with the object
  - wire_length:         wire length
  - instance_location:       instance location
  - pin_location:        pin location
  - module:              name of the subdesign
  - frc:                 file row column information
  - voltage:             voltage information
1
@genus:root: 25> report power>add32_power.rpt
Cannot find subcommand: power>add32_power.rpt
  report: generate one of various reports
Usage: report subcommand [-h]

  The 'subcommand' can be one of the following:
area                             - prints an area report
boundary_opto                    - reports boundary optimization summary
case_analysis                    - prints a case_analysis report
cdn_loop_breaker                 - reports the cdn_loop_breaker instances
cell_delay_calculation           - reports how the cell delay of a libcell instance is calculated
clock_gating                     - prints a clock-gating report
clock_groups                     - prints a clock groups report
clocks                           - prints a clock report
congestion                       - reports congestion summary
datapath                         - prints a datapath resources report
dedicated_clock_remapping_report - prints remap_to_dedicated_clock_library report
design_rules                     - prints design rule violations
dft_chains                       - reports DFT scan chains
dft_clock_domain_info            - reports DFT clock domain information with OPCG inserted logic
dft_core_wrapper                 - reports the IEEE 1500 core wrapper segments inserted for ports and pins
dft_registers                    - reports DFT status of registers
dft_setup                        - reports DFT setup for scan
dft_violations                   - reports DFT rule violations
dont_touch                       - prints a dont_touch report
gates                            - prints a gates report
hierarchy                        - prints a hierarchy report
instance                         - prints an instance report
low_power_intent                 - prints Power Intent report
memory                           - prints a memory usage report
memory_cells                     - print memory cells in the library
messages                         - prints a summary of error messages that have been issued
min_pulse_width                  - prints min pulse width violations
mode                             - prints a mode report
module                           - prints a module report
multibit_inferencing             - prints a multibit inferencing report
net_cap_calculation              - reports how the capacitance of the net is calculated
net_delay_calculation            - reports how the net delay is calculated
net_res_calculation              - reports how the resistance of the net is calculated
nets                             - prints a nets report
opcg_equivalents                 - reports the scan cell to OPCG cell equivalent mappings for cells specified using the 'set_opcg_equivalent' command
ple                              - reports physical layout estimation data
port                             - prints a port report
power                            - prints a power report
power_intent                     - prints Power Intent report
power_intent_instances           - prints Low Power cells report
property                         - list all the properties
proto                            - reports prototype synthesis information
qor                              - prints a QOR report
report_delay_calculation         - reports how the net and cell delay is calculated
report_ungroup_modules           - report ungrouped modules and instances
scan_compressibility             - reports the scan compressibility of the design having previously run the 'analyze_scan_compressibility' command
sequential                       - prints a sequential instance report
slew_calculation                 - reports how the slew on the driver pin of a libcell instance is calculated
summary                          - prints an area, timing, and design rules report
test_power                       - estimates the average scan power in shift and capture modes during test
timing                           - prints a timing report
units                            - reports units
utilization                      - reports how floorplan utilization is calculated
yield                            - prints a yield report
Failed on 'report power>add32_power.rpt'
@genus:root: 26> report timing -unconstrained>add32_timing.rpt
Error   : An invalid option was specified. [TUI-204] [_report_timing]
        : An option named '-unconstrained>add32_timing.rpt' could not be found.
  _report_timing: prints a timing report 

Usage: _report_timing [-fields <string>] [-output_format <string>]
           [-path_type <string>] [-split_delay] [-stage_delay] [-hpins] [-nets]
           [-exception_data] [-unconstrained] [-physical] [-user_derate]
           [-user_mean_derate] [-user_sigma_derate] [-incr_derate] [-gui]
           [-max_paths <integer>] [-nworst <integer>] [-logic_levels <integer>]
           [-skip_buf] [-skip_inv] [-logic_levels_tcl_list] [-max_slack <float>]
           [-min_slack <float>] [-paths <string>] [-domain <clock_domain>]
           [-views <analysis_view>+] [-collection]
           [ -from <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -from_rise <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -from_fall <inst|hinst|external_delay|clock|port|pin|hpin>+ ]
           [ -through <inst|hinst|hnet|port|pin|hpin>+ |
             -through_rise <inst|hinst|hnet|port|pin|hpin>+ |
             -through_fall <inst|hinst|hnet|port|pin|hpin>+ ]+
           [ -not_through <inst|hinst|hnet|port|pin|hpin>+ |
             -not_through_rise <inst|hinst|hnet|port|pin|hpin>+ |
             -not_through_fall <inst|hinst|hnet|port|pin|hpin>+ ]
           [ -to <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -to_rise <inst|hinst|external_delay|clock|port|pin|hpin>+ |
             -to_fall <inst|hinst|external_delay|clock|port|pin|hpin>+ ]
           [ -capture_clock_pins <pin|hpin>+ |
             -capture_clock_pins_rise_clock <pin|hpin>+ |
             -capture_clock_pins_fall_clock <pin|hpin>+ |
             -capture_clock_pins_rise_pin <pin|hpin>+ |
             -capture_clock_pins_fall_pin <pin|hpin>+ ]
           [-exceptions <exception>+] [-group <cost_group>+]
           [-timing_bin <timing_bin>] [-timing_path <timing_bin_path>]
           [<timing_path>+] [> file]

    [-fields <string>]:
        fields 
    [-output_format <string>]:
        supported output format types are <gtd|text> 
    [-path_type <string>]:
        supported path types are <full|summary|full_clock|endpoint> 
    [-split_delay]:
        displays both drivers and loads in the data path 
    [-stage_delay]:
        displays only drivers in the data path 
    [-hpins]:
        displays hierarchical pins in the data path 
    [-nets]:
        displays nets in the data path 
    [-exception_data]:
        displays the exception cross-linking information 
    [-unconstrained]:
        displays the unconstrained paths 
    [-physical]:
        include physical information in report 
    [-user_derate]:
        show 'user_derate' column in timing reports 
    [-user_mean_derate]:
        show 'user_mean_derate' column in timing reports 
    [-user_sigma_derate]:
        show 'user_sigma_derate' column in timing reports 
    [-incr_derate]:
        show 'incr_derate' column in timing reports 
    [-gui]:
        invoke GUI timing report dialog 
    [-max_paths <integer>]:
        number of paths 
    [-nworst <integer>]:
        number of worst paths to each endpoint (inapplicable to path_type 
        endpoint) 
    [-logic_levels <integer>]:
        number of paths to report in the output 
    [-skip_buf]:
        skip buffers when computing logic levels 
    [-skip_inv]:
        skip inverters when computing logic levels 
    [-logic_levels_tcl_list]:
        list output 
    [-max_slack <float>]:
        only paths with less than this slack 
    [-min_slack <float>]:
        only paths with greater than this slack 
    [-paths <string>]:
        a path identifier result from the specify_paths command 
    [-domain <clock_domain>]:
        a clock domain the paths should be restricted to 
    [-views <analysis_view>+]:
        a view the paths should be restricted to 
    [-collection]:
        return a collection of timing paths 
    -from <inst|hinst|external_delay|clock|port|pin|hpin>+:
        a set of startpoints for the paths 
    -from_rise <inst|hinst|external_delay|clock|port|pin|hpin>+:
        startpoints with a rise transition at the pin itself 
    -from_fall <inst|hinst|external_delay|clock|port|pin|hpin>+:
        startpoints with a fall transition at the pin itself 
    -through <inst|hinst|hnet|port|pin|hpin>+:
        specifies paths that pass through these pins or instances. This option 
        can be repeated indicating that the path must go through at least one 
        element of each through list (in the order the options were specified). 
        Objects must be ports, hierarchical pins, pins on sequential/mapped 
        combinational cells, or sequential/mapped combinational instances 
    -through_rise <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that contain a rise transition in one of 
        these objects and it can be repeated and can be combined with -through 
        and/or -through_fall_pin 
    -through_fall <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that contain a fall transition in one of 
        these objects and it can be repeated and can be combined with -through 
        and/or -through_rise_pin 
    -not_through <inst|hinst|hnet|port|pin|hpin>+:
        specifies paths that do not pass through these pins or instances. 
        Objects must be ports, hierarchical pins, pins on sequential/mapped 
        combinational cells, or sequential/mapped combinational instances 
    -not_through_rise <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that does not contain a rise transition in 
        one of these objects 
    -not_through_fall <inst|hinst|hnet|port|pin|hpin>+:
        this option specifies paths that does not contain a fall transition in 
        one of these objects 
    -to <inst|hinst|external_delay|clock|port|pin|hpin>+:
        a set of endpoints for the paths 
    -to_rise <inst|hinst|external_delay|clock|port|pin|hpin>+:
        endpoints with a rise transition at the pin itself 
    -to_fall <inst|hinst|external_delay|clock|port|pin|hpin>+:
        endpoints with a fall transition at the pin itself 
    -capture_clock_pins <pin|hpin>+:
        sequential clock pins at the path endpoint 
    -capture_clock_pins_rise_clock <pin|hpin>+:
        pins that capture with rising clock edge 
    -capture_clock_pins_fall_clock <pin|hpin>+:
        pins that capture with falling clock edge 
    -capture_clock_pins_rise_pin <pin|hpin>+:
        pins that capture with rise transition at the pin itself 
    -capture_clock_pins_fall_pin <pin|hpin>+:
        pins that capture with fall transition at the pin itself 
    [-exceptions <exception>+]:
        report paths for exceptions 
    [-group <cost_group>+]:
        report paths for the specified cost groups/path groups 
    [-timing_bin <timing_bin>]:
        timing bin to report 
    [-timing_path <timing_bin_path>]:
        timing path to report 
    [<timing_path>+]:
        path_collection 
Fields presented are controlled by the '-fields' switch or the attribute
'timing_report_fields' and 'timing_report_endpoint_fields'
Valid full report fields are:
  - timing_point:        names of pins
  - flags:               flags associated with the column timing_point
  - arc:                 timing arc for which timing information was applied
  - edge:                rising/falling edge
  - cell:                cell type, exception type, etc.
  - fanout:              fanout of leaf cells
  - load:                load of leaf cells
  - transition:          slew of leaf cell outputs
  - transition_mean:     mean slew of leaf cell outputs
  - transition_sigma:    sigma slew of leaf cell outputs
  - delay:               delay through a leaf cell
  - delay_mean:          mean delay through a leaf cell
  - delay_sigma:         sigma delay through a leaf cell
  - arrival:             arrival time at a leaf cell
  - arrival_mean:        mean arrival time at a leaf cell
  - arrival_sigma:       sigma arrival time at a leaf cell
  - lib_set:             display the library set of the cell
  - user_derate:         derating information
  - user_mean_derate:    mean derating information
  - user_sigma_derate:   derating information
  - total_derate:        total derating information
  - incr_derate:        incr derating information
  - aocv_derate:         aocv derating information
  - socv_derate:         socv spatial derating information
  - stage_count:         aocv stage depth
  - power_domain:        power domain associated with the object
  - wire_length:         wire length
  - instance_location:       instance location
  - pin_location:        pin location
  - module:              name of the subdesign
  - frc:                 file row column information
  - voltage:             voltage information
1
@genus:root: 27> report power > add32_power.rpt
Info    : Joules engine is used. [RPT-16]
        : Joules engine is being used for the command report_power.
Info   : ACTP-0001 [ACTPInfo] Activity propagation started for stim#0 netlist
       : add32
Info   : ACTP-0009 [ACTPInfo] Activity Propagation Progress Report :   0%   1%   2%   3%   4%   5%   6%   7%   8%   9%  10%  11%  12%  13%  14%  15%  16%  17%  18%  19%  20%  21%  22%  23%  24%  25%  26%  27%  28%  29%  30%  31%  32%  33%  34%  35%  36%  37%  38%  39%  40%  41%  42%  43%  44%  45%  46%  47%  48%  49%  50%  51%  52%  53%  54%  55%  56%  57%  58%  59%  60%  61%  62%  63%  64%  65%  66%  67%  68%  69%  70%  71%  72%  73%  74%  75%  76%  77%  78%  79%  80%  81%  82%  83%  84%  85%  86%  87%  88%  89%  90%  91%  92%  93%  94%  95%  96%  97%  98%  99% 100%
Info   : ACTP-0001 Activity propagation ended for stim#0
Info   : PWRA-0001 [PwrInfo] compute_power effective options 
       : -mode : vectorless
       : -skip_propagation : 1
       : -frequency_scaling_factor : 1.0
       : -use_clock_freq : stim
       : -stim :/stim#0
       : -fromGenus : 1
Info   : ACTP-0001 Timing initialization started
Info   : ACTP-0001 Timing initialization ended
Info   : PWRA-0002 [PwrInfo] Skipping activity propagation due to -skip_ap
       : option....
Warning: PWRA-0302 [PwrWarn] Frequency scaling is not applicable for vectorless
       : flow. Ignoring frequency scaling.
Warning: PWRA-0304 [PwrWarn] -stim option is not applicable with vectorless mode
       : of power analysis, ignored this option.
Info   : PWRA-0002 Started 'vectorless' power computation.
Info   : PWRA-0009 [PwrInfo] Power Computation Progress Report :   0%   1%   2%   3%   4%   5%   6%   7%   8%   9%  10%  11%  12%  13%  14%  15%  16%  17%  18%  19%  20%  21%  22%  23%  24%  25%  26%  27%  28%  29%  30%  31%  32%  33%  34%  35%  36%  37%  38%  39%  40%  41%  42%  43%  44%  45%  46%  47%  48%  49%  50%  51%  52%  53%  54%  55%  56%  57%  58%  59%  60%  61%  62%  63%  64%  65%  66%  67%  68%  69%  70%  71%  72%  73%  74%  75%  76%  77%  78%  79%  80%  81%  82%  83%  84%  85%  86%  87%  88%  89%  90%  91%  92%  93%  94%  95%  96%  97%  98%  99% 100%
Info   : PWRA-0002 Finished power computation.
Info   : PWRA-0007 [PwrInfo] Completed successfully.
       : Info=6, Warn=2, Error=0, Fatal=0
Output file: add32_power.rpt
@genus:root: 28> report area > add32_area.rpt
Warning : The details given in report might be incorrect or incomplete. [RPT-80]
        : The design design:add32 should be mapped to get accurate area details.
        : Map the design using syn_map before using the '-detail' option of the 'report_area' command.
@genus:root: 29> write_hdl > add32_netlist.v
@genus:root: 30> gui_show
